name: Feature CI

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload test coverage artifacts
        uses: actions/upload-artifact@v3
        with:
            name: jacoco-test-coverage-report
            path: build/reports/jacoco/test/html/
#      - name: Download test coverage artifacts
#        uses: actions/download-artifact@v3
#        with:
#          path: build/reports/jacoco/test/html/
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: kimgoetzke/practice-feature
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
